set Global local_infile=1;
CREATE DATABASE LAB04_2019E166;
USE LAB04_2019E166;
CREATE TABLE SAMPLE_POPULATION
(CountryCode INT, CountryName VARCHAR(20), Year YEAR, RaceCode INT, 
RaceName VARCHAR(100),Gender VARCHAR(10) , Age INT , Population INT	
);
CREATE TABLE POPULATION
(CountryCode INT, CountryName VARCHAR(20), Year YEAR, RaceCode INT, 
RaceName VARCHAR(100),Gender VARCHAR(10) , Age INT , Population INT	
);

LOAD DATA LOCAL INFILE 'C:/Users/TEMP.jfn.001/Downloads.Population.csv'
INTO TABLE POPULATION FIELDS TERMINATED BY ',' ENCLOSED
BY '"' LINES TERMINATED 
BY '\n' IGNORE 1 ROWS;

SELECT 
